---
- name: Generate redis config files.
  template:
    src: {{ item }}.json.j2
    dest: /etc/sensu/conf.d/sensu-framework/{{ item }}.json
    owner: "{{ sensu_user }}"
    group: "{{ sensu_group }}"
    mode: "u=rw,g=r,o=r"
  with_items:
    - redis
  



