---
- name: sshd configuration | Generate the config file 
  template:   
    src: etc_ssh_sshd_config.j2 
    dest: /etc/hosts

- name: sshd configuration | Restart SSH
  service: 
    name: ssh 
    state: restarted
