---
# Variable to control the installation
sensu_install_client: true
sensu_install_server: true
sensu_install_uchiwa: true

#Sensu embedded ruby use ? 
sensu_embedded_ruby: true

#User/Group for install processes
sensu_user: root
sensu_group: root

sensu_settings: {}

# Sensu SSL Certificates
sensu_cert_dir: "/home/ansible/files/sensu-server/ssl/"
sensu_cert_file_name: "cert.pem"
sensu_key_file_name: "key.pem"

# Redis variables 
sensu_server_redis_hostname: "127.0.0.1"
sensu_server_redis_port: "6379"

#Rabbitmq variables - This is the RabbitMQ TLS port, if you choose to not use a secure connection, change that and the following boolean to false.
sensu_server_rabbitmq_secure: true
sensu_server_rabbitmq_hostname: "127.0.0.1"
sensu_server_rabbitmq_port: "5671"
sensu_server_rabbitmq_vhost: "/sensu"
sensu_server_rabbitmq_user: "sensu"
sensu_server_rabbitmq_password: "placeholder"

# Sensu Server API variable
sensu_checks_dir: "/home/ansible/files/sensu-server/checks/"
sensu_server_api_hostname: "127.0.0.1"
sensu_server_api_port: 4567
sensu_server_api_user: "sensu"
sensu_server_api_password: "placeholder"

# Sensu client variables
sensu_client_hostname: "{{ ansible_hostname }}"
sensu_client_address: "127.0.0.1"


# Uchiwa (Snesu-frontend) variables 
sensu_datacenter_uchiwa: "scw.cloud.minsys.io"
sensu_server_dashboard_host: "0.0.0.0"
sensu_server_dashboard_port: "3000"
sensu_server_dashboard_user: "minsys"
sensu_server_dashboard_password: "placeholder"
sensu_server_dashboard_refresh:  5


#sensu_checks:   []
#sensu_handlers: []
#sensu_server_patch_init_scripts: true


#telemetry.prd.123.cloud.minsys.io -> cloud.minsys.io 
#scw-head.prd.scw.cloud.minsys.io  -> scw.cloud.minsys.io (Scaleway)
#ovh-head.prd.ovh.cloud.minsys.io  -> ovh.cloud.minsys.io ( OVH.com )
#aws-head.prd.aws.cloud.minsys.io  -> aws.cloud.minsys.io ( Amazon Web Services )
#gcp-head.prd.gcp.cloud.minsys.io -> gcp.cloud.minsys.io ( Google Cloud Platform )
#arc-head.prd.arc.cloud.minsys.io -> arc.cloud.minsys.io ( Aruba Cloud )
#dgo-head.prd.dgo.cloud.minsys.io -> dgo.cloud.minsys.io ( Digital Ocean )
#joy-head.prd.joy.cloud.minsys.io -> joy.cloud.minsys.io ( Joyent )



