---

#Commandline : EXAMPLE
#ansible-playbook -e “password=azerty123” /etc/ansible/roles/postinstall/setup.yml

- name: 'Yet another Ansible playbook to set the motd' 
  become: true
  become_user: root
  become_method: sudo
  roles:
    - motd-ovh