---
#User/Group for install processes
sensu_user: root
sensu_group: root

#Custom client.json config
sensu_client_hostname: "{{ ansible_hostname }}"
sensu_client_address: "{{ ansible_fqdn }}"
sensu_client_env: "{{ prompted_env }}"

# Sensu SSL Certificates
sensu_cert_file_name: "cert.pem"
sensu_key_file_name: "key.pem"

#rabbitmq.json config parameters
sensu_server_rabbitmq_hostname: "ovh.cloud.minsys.io"
sensu_server_rabbitmq_port: "5671"
sensu_server_rabbitmq_vhost: "/sensu"
sensu_server_rabbitmq_user: "sensu"
sensu_server_rabbitmq_password: "pass"






