---
- name: Check the current time zone 
  shell: cat /etc/timezone
  register: current_tzone  

- name: Set timezone variables to Europe/Paris
  copy: 
    content: "{{ timezone.my_tzone }}"
    dest: /etc/timezone
    owner: root
    group: root
    mode: 0644
    backup: yes
  when: current_tzone.stdout != timezone.my_tzone
  notify: Update_Timezone