---
- name: Check if the rancher-agent is running, normally it doesn't !  
  command: docker ps -a
  register: containers

- name: Register the Host machine with the Rancher server
  docker:
      image: rancher/agent:v1.0.1
      privileged: yes
      detach: True
      volumes: /var/run/docker.sock:/var/run/docker.sock
      command: http://docker-forge.cloud.minsys.io:8080/v1/scripts/890BC456305F2DEEEB39:1463954400000:RyUdeO9sdNCom396sHwDZKofts
      state: started
  when: "{{ 'rancher-agent' not in containers.stdout }}"
