---
#ansible-playbook /etc/ansible/roles/setup_postinstall-scw.yaml

- name: 'Postinstall Routine for Scaleway hosts'
  hosts: scw_newinstances
  roles:
    - dist_update_upgrade-scw
    - timezone-scw
    - etc_hosts-scw
    - addgroups_initial-scw
    - adduser_lvi-scw
    - adduser_cso-scw
    - ssh_config-scw
    - fail2ban-scw
    - motd-scw
  post_tasks:
    - name:  Restart rsyslog to sync with newly intalled timezone 
      service: name=rsyslog state=restarted
