---
#Initial password to be changed at first boot
init_password: "{{ prompted_pass }}"

#Timezone 
timezone:
  my_tzone: "Europe/Paris"

#/etc/hosts configuration
sensu_client_hostname: "{{ ansible_hostname }}"
sensu_client_env: "{{ prompted_env }}"

#/etc/ssh/sshd_config configuration
ssh_bind_port: "22"

#Fail2Ban configuration
fail2ban:
  config:
    ignoreip: 127.0.0.1/8
    bantime: 600
    findtime: 600
    maxretry: 3
    backend: auto
    usedns: warn
    destemail: root@localhost
    sendername: Fail2Ban
    banaction: iptables-multiport
    mta: sendmail
    protocol: tcp
    chain: INPUT

#Sensu-client configuration 
#User/Group for pkg install processes
sensu_user: root
sensu_group: root

#Custom client.json config
sensu_client_fqdn: "{{ ansible_fqdn }}"
#Following are already defined in the /etc/hosts configuration
#sensu_client_hostname: "{{ ansible_hostname }}"
#sensu_client_env: "{{ prompted_env }}"


# Sensu SSL Certificates
sensu_cert_file_name: "cert.pem"
sensu_key_file_name: "key.pem"

#rabbitmq.json config parameters
sensu_server_rabbitmq_hostname: "scw.cloud.minsys.io"
sensu_server_rabbitmq_port: "5671"
sensu_server_rabbitmq_vhost: "/sensu"
sensu_server_rabbitmq_user: "sensu"
sensu_server_rabbitmq_password: "pass"


